### ISSUE TITLE
Nest formulier

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#476]
## Todo @peterdesmet 

- [x] CSS naar `assets` (no css)
- [x] script to `assets`

## Todo iAsset

- [x] Bootstrap: 5.1.3 ipv 5.3.0
- [x] jQuery: 3.6.0 ipv 3.6.3
- [x] jQuery-ui: waarvoor wordt dit gebruikt? **Not needed, removed**
- [x] Niet `form-group` gebruiken, maar:

```html
<form class="row">
  <div class="col-md-6">
    <label for="e-mailadres" class="form-label">E-mailadres</label>
    <input type="email" class="form-control" id="e-mailadres">
  </div>
  <div class="col-md-6">
    ...
   ...
```

- [x] Verplichte velden aanduiden
  - [x] datum van observatie
  - [x] locatie
  - [x] foto 1
  - [x] naam
  - [x] telefoon
  - [x] emailadres
- [x] Foutmelding geven als verplicht veld niet is ingevuld
- [x] Weinig validatie op velden
  - [x] email
  - [x] telefoon
- [x] Maak gebruik van Bootstrap validation: https://getbootstrap.com/docs/5.0/forms/validation/
- [x] Verwijder "Melding:"
- [x] Nederlandse en Engelstalige veldnamen + indien-knop
- [x] Betere mobiele display (`col` aanpassen)
- [x] Maak van `Datum/tijd registratie` een hidden field met current date (of aan API kant)
- [x] Hernoem `GPS` naar `Coördinaten`
- [x] Google Maps: momenteel is er een overlay `for development purposes only`
- [x] Waarvoor dient `Gegevens bewaren`
- [x] Hernoem `Mogen wij uw gegevens bewaren?`
- [x] Bevestiging hernoemen van `success` naar iets informatiever

**Comment by peterdesmet** [comment]
- [ ] Use `mb-3` rather than cols. Remove `mb-3` from `form-control` + remove `row` on form 
- [ ] Add ` novalidate` to form (see https://getbootstrap.com/docs/5.0/forms/validation/#custom-styles) to disable browser defaults
- [ ] Rename `meldingen` to `nest-report-form`
- [ ] No colon after labels
- [ ] Use `col-label`, not ` col-form-label`
- [ ] Rename `Het veld is verplicht!` to `Dit veld is verplicht.`
- [ ] Also indicate `Dit veld is verplicht.` for foto 1.
- [ ] Can we make use of Open Street Map, so we don't need a Google maps key?
- [ ] `Mogen we uw gegevens bewaren`: purpose of field to be discussed with @jrhillae
- [ ] Test submission server side

**Comment by jrhillae** [comment]
@peterdesmet : **what is the purpose of Mogen we uw gegevens bewaren? What if the user clicks no.** -> This was necessary for iAsset, they need explicit consent of the user that they are allowed to store personal information. 
If the user clicks no, the report can not be submitted. 
We are not only storing the data, but can also contact a person regarding its report or give this contact info to an erradicator to arrange a timing for nest management.

**Should coordinaten be mandatory`**?: Yes, coordinaten should be mandatory.
